const { expect } = require("chai");

//expect().toBe()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
expect().tobe();
//expect().to.equal()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
expect().to.equal();
//expect().to.not.equal()とは、期待値と実際の値が一致しないかどうかをテストするためのメソッドです。
expect().to.not.equal();
//expect().to.be.true()とは、期待値がtrueであるかどうかをテストするためのメソッドです。
expect().to.be.true();
//expect().to.be.false()とは、期待値がfalseであるかどうかをテストするためのメソッドです。
expect().to.be.false();
//expect().to.be.null()とは、期待値がnullであるかどうかをテストするためのメソッドです。
expect().to.be.null();
//expect().to.be.undefined()とは、期待値がundefinedであるかどうかをテストするためのメソッドです。
expect().to.be.undefined();
//expect().to.be.ok()とは、期待値がtrueであるかどうかをテストするためのメソッドです。
expect().to.be.ok();
//expect().to.be.not.ok()とは、期待値がfalseであるかどうかをテストするためのメソッドです。
expect().to.be.not.ok();
//assert()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
assert();
//assert.equal()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
assert.equal();
//assert.notEqual()とは、期待値と実際の値が一致しないかどうかをテストするためのメソッドです。
assert.notEqual();
//assert.strictEqual()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
assert.strictEqual();
//assert.notStrictEqual()とは、期待値と実際の値が一致しないかどうかをテストするためのメソッドです。
assert.notStrictEqual();
//assert.deepEqual()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
assert.deepEqual();
//assert.notDeepEqual()とは、期待値と実際の値が一致しないかどうかをテストするためのメソッドです。
assert.notDeepEqual();
//assert.deepStrictEqual()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
assert.deepStrictEqual();
//assert.notDeepStrictEqual()とは、期待値と実際の値が一致しないかどうかをテストするためのメソッドです。
assert.notDeepStrictEqual();
//assert.fail()とは、テストを失敗させるためのメソッドです。
assert.fail();
//assert.throws()とは、関数が例外を投げるかどうかをテストするためのメソッドです。
assert.throws();
//assert.doesNotThrow()とは、関数が例外を投げないかどうかをテストするためのメソッドです。
assert.doesNotThrow();
//assert.ifError()とは、エラーが発生しないかどうかをテストするためのメソッドです。
assert.ifError();
//expect().to.equal()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
expect().to.equal();
//expect().to.deep.include()とは、期待値が実際の値を含むかどうかをテストするためのメソッドです。
expect().to.deep.include();
//expect().to.have.deep.members()とは、期待値が実際の値を含むかどうかをテストするためのメソッドです。
expect().to.have.deep.members();
//expect().to.have.property()
//assert.fail()とは、テストを失敗させるためのメソッドです。
assert.fail();
//assert().isOk()とは、期待値がtrueであるかどうかをテストするためのメソッドです。
assert().isOk();
//assert().isNotOk()とは、期待値がfalseであるかどうかをテストするためのメソッドです。
assert().isNotOk();
//assert().equal()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
assert().equal();
//assert().notEqual()とは、期待値と実際の値が一致しないかどうかをテストするためのメソッドです。
assert().notEqual();
//assert().strictEqual()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
assert().strictEqual();
//assert().notStrictEqual()とは、期待値と実際の値が一致しないかどうかをテストするためのメソッドです。
assert().notStrictEqual();
//assert().deepEqual()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
assert().deepEqual();
//assert().notDeepEqual()とは、期待値と実際の値が一致しないかどうかをテストするためのメソッドです。
assert().notDeepEqual();
//assert().deepStrictEqual()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
assert().deepStrictEqual();
//assert().notDeepStrictEqual()とは、期待値と実際の値が一致しないかどうかをテストするためのメソッドです。
assert().notDeepStrictEqual();
//assert().fail()とは、テストを失敗させるためのメソッドです。
assert().fail();
//assert().throws()とは、関数が例外を投げるかどうかをテストするためのメソッドです。
assert().throws();
//assert().doesNotThrow()とは、関数が例外を投げないかどうかをテストするためのメソッドです。
assert().doesNotThrow();
//assert().ifError()とは、エラーが発生しないかどうかをテストするためのメソッドです。
assert().ifError();
//expect().to.equal()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
expect().to.equal();
//expect().to.deep.include()とは、期待値が実際の値を含むかどうかをテストするためのメソッドです。
expect().to.deep.include();
//expect().to.have.deep.members()とは、期待値が実際の値を含むかどうかをテストするためのメソッドです。
expect().to.have.deep.members();
//expect().to.have.property()
//assert.fail()とは、テストを失敗させるためのメソッドです。
assert.fail();
//assert().isOk()とは、期待値がtrueであるかどうかをテストするためのメソッドです。
assert().isOk();
//assert().isNotOk()とは、期待値がfalseであるかどうかをテストするためのメソッドです。
assert().isNotOk();
//assert().equal()とは、期待値と実際の値が一致するかどうかをテストするためのメソッドです。
assert().equal();
