//executeBlock()とは、ブロックの実行を行う関数である。
api.call.core.executeBlock
//accountCodeAt()とは、アカウントのコードを取得する関数である。
api.query.system.accountCodeAt
//currentAll()とは、現在のブロックを取得する関数である。
api.call.ethereumRuntimeRPCApi.currentAll
//currentTransactionStatuses()とは、現在のトランザクションの状態を取得する関数である。
api.call.ethereumRuntimeRPCApi.currentTransactionStatuses
//elasticiy()とは、Elasticityを取得する関数である。
api.query.ethereum.elasticiy
//currentBlock()とは、現在のブロックを取得する関数である。
api.call.ethereumRuntimeRPCApi.currentBlock
//currentReceipts()とは、現在のレシートを取得する関数である。
api.call.ethereumRuntimeRPCApi.currentReceipts
//extrinsicFilter()とは、ExtrinsicFilterを取得する関数である。
api.query.ethereum.extrinsicFilter
//storageAt()とは、ストレージを取得する関数である。
api.call.ethereumRuntimeRPCApi.storageAt
//generateKeyOwnershipProof()とは、キーの所有権証明書を生成する関数である。
api.call.ethereumRuntimeRPCApi.generateKeyOwnershipProof
//grandpaAuthorities()とは、GrandpaAuthoritiesを取得する関数である。
api.query.ethereum.grandpaAuthorities
//mmrRoot()とは、MMRRootを取得する関数である。
api.query.ethereum.mmrRoot
//verifyBatchProof()とは、バッチ証明書を検証する関数である。
api.call.ethereumRuntimeRPCApi.verifyBatchProof
//availableBlockHash()とは、利用可能なブロックハッシュを取得する関数である。
api.query.ethereum.availableBlockHash
//candidateEvents()とは、候補イベントを取得する関数である。
api.query.ethereum.candidateEvents
//disputePeriod()とは、DisputePeriodを取得する関数である。
api.query.ethereum.disputePeriod
//executeBlock()とは、ブロックの実行を行う関数である。
api.call.ethereumRuntimeRPCApi.executeBlock
//dmqContents()とは、DMQContentsを取得する関数である。
api.query.ethereum.dmqContents

