#docker-compose書き方
#mysql
mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: test
    MYSQL_USER: test
    MYSQL_PASSWORD: test
  volumes:
    - ./mysql:/var/lib/mysql
  restart: always
  #nodejs
nodejs:
  build: ./nodejs
  ports:
    - "3000:3000"
  volumes:
    - ./nodejs:/usr/src/app
  links:
    - mysql
  restart: always
  #postgres
postgres:
  image: postgres:9.6
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: root
    POSTGRES_USER: test
    POSTGRES_DB: test
  volumes:
    - ./postgres:/var/lib/postgresql/data
  restart: always